server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customersService
          uri: lb://CUSTOMERS-SERVICE
          predicates:
            - Path=/customers/**
        - id: addressesService
          uri: lb://ADDRESSES-SERVICE
          predicates:
            - Path=/addresses/**
        - id: webUIService
          uri: lb://WEB-UI-SERVICE
          predicates:
            - Path=/index,/**.js